### ISSUE TITLE
Error: Module name must be provided or Collector needs to be bound to a module

### ISSUE THREAD

**Issue by mischw** [fox-it/acquire#59]
I am having trouble using dissects acquire. When using it with the file option everything is fine:
```
*** Acquiring specified paths
- Collecting file /root/.bashrc: OK

Done collecting artifacts:
------------------------------------------------------------
  Module |    Success |    Failure |    Missing |      Empty
------------------------------------------------------------
cli-args |          1 |            |            |
------------------------------------------------------------
   Total |          1 |          0 |          0 |          0
------------------------------------------------------------
```

But when using the glob option I can't seem to get any files out of the image. The following error suggests providing a module name which I am not sure how to do. Am I missing something? Any advice is much appreciated.
```
*** Acquiring specified paths
- Collecting glob /root/.*shrc
- Failed to collect glob /root/.*shrc
Traceback (most recent call last):
  File "/root/py3venv_dissect/lib/python3.10/site-packages/acquire/collector.py", line 361, in collect_glob
    self.collect_path(entry)
  File "/root/py3venv_dissect/lib/python3.10/site-packages/acquire/collector.py", line 381, in collect_path
    raise ValueError("Module name must be provided or Collector needs to be bound to a module")
ValueError: Module name must be provided or Collector needs to be bound to a module

Done collecting artifacts:
------------------------------------------------------------
  Module |    Success |    Failure |    Missing |      Empty
------------------------------------------------------------
cli-args |            |          1 |            |
------------------------------------------------------------
   Total |          0 |          1 |          0 |          0
------------------------------------------------------------ 
```

**Comment by Schamper** [comment]
Thanks! Looks like a missing argument to one of the underlying function calls when collecting a glob pattern. #60 will fix this.
